package com.admtechhub.maestrohr.platform;

import com.admtechhub.maestrohr.auth.User;
import com.admtechhub.maestrohr.tenant.Tenant;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Types;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Phase E4c-ii — privileged writes for the tenant / user provisioning paths that operate
 * with no tenant session (registration) or across tenants (SUPER_ADMIN CRUD).
 *
 * <p>These are the write counterparts of {@link AuthBootstrapQueries} / {@link AdminStatsQueries}.
 * Under the RLS-enforced {@code maestro_app} primary they cannot run on the scoped JPA path:
 * <ul>
 *   <li>A new {@code tenants} row's id is generated by Hibernate at persist time, so its session
 *       cannot be bound to {@code app.current_tenant} <em>before</em> the insert — the RLS
 *       {@code WITH CHECK (id = current_tenant)} is therefore unsatisfiable for tenant creation.</li>
 *   <li>A SUPER_ADMIN carries their own tenant in session, so creating/updating any <em>other</em>
 *       tenant's rows fails the policy.</li>
 * </ul>
 * Routed through the privileged (postgres) datasource they bypass RLS, exactly as the matching
 * reads already do. The ids are generated here in Java so callers get them back without a
 * {@code RETURNING} round-trip.
 *
 * <p>The privileged template's connections are auto-commit, so each public method that issues a
 * single statement commits on its own. {@link #provisionTenantWithAdmin} groups its two inserts
 * into one explicit transaction on a single connection so a registration is all-or-nothing.
 */
@Repository
public class TenantUserWrites {

    private static final String INSERT_TENANT =
            "INSERT INTO tenants (id, company_name, rc_number, industry, company_size, "
                    + "subscription_plan, subscription_expires_at, is_active) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

    private static final String INSERT_USER =
            "INSERT INTO users (id, tenant_id, email, password_hash, role, is_active) "
                    + "VALUES (?, ?, ?, ?, ?, ?)";

    private static final String UPDATE_TENANT =
            "UPDATE tenants SET company_name = ?, rc_number = ?, industry = ?, company_size = ?, "
                    + "subscription_plan = ?, subscription_expires_at = ?, is_active = ? WHERE id = ?";

    private static final String UPDATE_USER =
            "UPDATE users SET tenant_id = ?, email = ?, role = ?, is_active = ?, "
                    + "failed_login_attempts = ?, locked_until = ?, password_hash = ? WHERE id = ?";

    private final JdbcTemplate jdbc;

    public TenantUserWrites(@Qualifier("privilegedJdbcTemplate") JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    /** Insert a single tenant (admin create-tenant). Assigns and back-fills its generated id. */
    public void insertTenant(Tenant tenant) {
        jdbc.execute((Connection con) -> {
            insertTenant(con, tenant);
            return null;
        });
    }

    /** Insert a single user (admin create-user). The tenant must already exist (FK). */
    public void insertUser(User user) {
        jdbc.execute((Connection con) -> {
            insertUser(con, user);
            return null;
        });
    }

    /**
     * Atomically provision a new tenant and its first admin user (registration). Both rows are
     * inserted on one connection inside a single transaction; the user's {@code tenant_id} is
     * wired to the freshly generated tenant id. On any failure nothing is committed, so a failed
     * user insert can never leave an orphan tenant. Both objects have their generated ids set.
     */
    public void provisionTenantWithAdmin(Tenant tenant, User adminUser) {
        jdbc.execute((Connection con) -> {
            boolean previousAutoCommit = con.getAutoCommit();
            con.setAutoCommit(false);
            try {
                insertTenant(con, tenant);
                adminUser.setTenantId(tenant.getId());
                insertUser(con, adminUser);
                con.commit();
            } catch (SQLException | RuntimeException e) {
                con.rollback();
                throw e;
            } finally {
                con.setAutoCommit(previousAutoCommit);
            }
            return null;
        });
    }

    /**
     * Suspend a tenant: cancel the subscription and deactivate the tenant row atomically.
     * @return false if no subscription row exists for the given tenantId (tenant not found / not provisioned)
     */
    public boolean suspendTenant(UUID tenantId) {
        Boolean result = jdbc.execute((Connection con) -> {
            boolean prev = con.getAutoCommit();
            con.setAutoCommit(false);
            try {
                int subRows;
                try (PreparedStatement ps = con.prepareStatement(
                        "UPDATE tenant_subscriptions SET status = 'CANCELLED' WHERE tenant_id = ?")) {
                    ps.setObject(1, tenantId);
                    subRows = ps.executeUpdate();
                }
                if (subRows == 0) {
                    con.rollback();
                    return false;
                }
                try (PreparedStatement ps = con.prepareStatement(
                        "UPDATE tenants SET is_active = false WHERE id = ?")) {
                    ps.setObject(1, tenantId);
                    ps.executeUpdate();
                }
                con.commit();
                return true;
            } catch (SQLException | RuntimeException e) {
                con.rollback();
                throw e;
            } finally {
                con.setAutoCommit(prev);
            }
        });
        return Boolean.TRUE.equals(result);
    }

    /**
     * Reactivate a tenant: set subscription status to ACTIVE, extend the period end by 30 days
     * (from whichever is later — the existing end or now), and re-enable the tenant row.
     * @return false if no subscription row exists for the given tenantId
     */
    public boolean reactivateTenant(UUID tenantId) {
        Boolean result = jdbc.execute((Connection con) -> {
            boolean prev = con.getAutoCommit();
            con.setAutoCommit(false);
            try {
                int subRows;
                try (PreparedStatement ps = con.prepareStatement(
                        "UPDATE tenant_subscriptions SET status = 'ACTIVE', "
                        + "current_period_end = GREATEST(COALESCE(current_period_end, now()), now()) + INTERVAL '30 days' "
                        + "WHERE tenant_id = ?")) {
                    ps.setObject(1, tenantId);
                    subRows = ps.executeUpdate();
                }
                if (subRows == 0) {
                    con.rollback();
                    return false;
                }
                try (PreparedStatement ps = con.prepareStatement(
                        "UPDATE tenants SET is_active = true WHERE id = ?")) {
                    ps.setObject(1, tenantId);
                    ps.executeUpdate();
                }
                con.commit();
                return true;
            } catch (SQLException | RuntimeException e) {
                con.rollback();
                throw e;
            } finally {
                con.setAutoCommit(prev);
            }
        });
        return Boolean.TRUE.equals(result);
    }

    /** Full-replace update of a tenant by id (admin update-tenant). @return whether the row existed. */
    public boolean updateTenant(Tenant tenant) {
        int rows = jdbc.update(UPDATE_TENANT,
                tenant.getCompanyName(),
                tenant.getRcNumber(),
                tenant.getIndustry(),
                tenant.getCompanySize(),
                tenant.getSubscriptionPlan().name(),
                tenant.getSubscriptionExpiresAt(),
                tenant.isActive(),
                tenant.getId());
        return rows > 0;
    }

    /**
     * Full-replace update of a user by id (admin update-user). The caller merges partial request
     * fields over the current row (read via {@link AuthBootstrapQueries#findUserById}) before
     * calling this, so every column is written explicitly. @return whether the row existed.
     */
    public boolean updateUser(User user) {
        int rows = jdbc.update(con -> {
            PreparedStatement ps = con.prepareStatement(UPDATE_USER);
            ps.setObject(1, user.getTenantId());
            ps.setString(2, user.getEmail());
            ps.setString(3, user.getRole().name());
            ps.setBoolean(4, user.isActive());
            ps.setInt(5, user.getFailedLoginAttempts());
            if (user.getLockedUntil() != null) {
                ps.setObject(6, user.getLockedUntil());
            } else {
                ps.setNull(6, Types.TIMESTAMP_WITH_TIMEZONE);
            }
            ps.setString(7, user.getPasswordHash());
            ps.setObject(8, user.getId());
            return ps;
        });
        return rows > 0;
    }

    // ── shared insert helpers (run on the caller's connection) ────────────────────────────

    private void insertTenant(Connection con, Tenant tenant) throws SQLException {
        if (tenant.getId() == null) {
            tenant.setId(UUID.randomUUID());
        }
        stampTimestamps(tenant::getCreatedAt, tenant::setCreatedAt, tenant::getUpdatedAt, tenant::setUpdatedAt);
        try (PreparedStatement ps = con.prepareStatement(INSERT_TENANT)) {
            ps.setObject(1, tenant.getId());
            ps.setString(2, tenant.getCompanyName());
            ps.setString(3, tenant.getRcNumber());
            ps.setString(4, tenant.getIndustry());
            ps.setString(5, tenant.getCompanySize());
            ps.setString(6, tenant.getSubscriptionPlan().name());
            ps.setObject(7, tenant.getSubscriptionExpiresAt());
            ps.setBoolean(8, tenant.isActive());
            ps.executeUpdate();
        }
    }

    private void insertUser(Connection con, User user) throws SQLException {
        if (user.getId() == null) {
            user.setId(UUID.randomUUID());
        }
        stampTimestamps(user::getCreatedAt, user::setCreatedAt, user::getUpdatedAt, user::setUpdatedAt);
        try (PreparedStatement ps = con.prepareStatement(INSERT_USER)) {
            ps.setObject(1, user.getId());
            ps.setObject(2, user.getTenantId());
            ps.setString(3, user.getEmail());
            ps.setString(4, user.getPasswordHash());
            ps.setString(5, user.getRole().name());
            ps.setBoolean(6, user.isActive());
            ps.executeUpdate();
        }
    }

    /**
     * The {@code created_at}/{@code updated_at} columns default to {@code NOW()} in the DB, but
     * Hibernate's {@code @CreationTimestamp}/{@code @UpdateTimestamp} normally populate them — so
     * we set them here too, purely so the in-memory object returned to the caller (and serialized
     * into the API response) carries the same timestamps the row got.
     */
    private void stampTimestamps(java.util.function.Supplier<OffsetDateTime> getCreated,
                                 java.util.function.Consumer<OffsetDateTime> setCreated,
                                 java.util.function.Supplier<OffsetDateTime> getUpdated,
                                 java.util.function.Consumer<OffsetDateTime> setUpdated) {
        OffsetDateTime now = OffsetDateTime.now();
        if (getCreated.get() == null) {
            setCreated.accept(now);
        }
        if (getUpdated.get() == null) {
            setUpdated.accept(now);
        }
    }
}
